# Generated by Django 5.2.3 on 2025-06-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="sum",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(100.0)],
                verbose_name="Сумма",
            ),
        ),
    ]
