# Generated by Django 5.2.3 on 2025-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_course_product_alter_lesson_description_and_more"),
        ("users", "0003_alter_payment_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="courses_bought",
            field=models.ManyToManyField(
                to="materials.course", verbose_name="Купленные курсы"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lessons_bought",
            field=models.ManyToManyField(
                to="materials.lesson", verbose_name="Купленные уроки"
            ),
        ),
    ]
