# Generated by Django 5.2.3 on 2025-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_courses_bought_customuser_lessons_bought"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.CharField(
                blank=True, verbose_name="Идентификатор сессии покупки"
            ),
        ),
        migrations.DeleteModel(
            name="UsersControl",
        ),
    ]
