# Generated by Django 5.2.3 on 2025-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
