# Generated by Django 5.2.3 on 2025-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="seq_number",
            field=models.IntegerField(default=0),
        ),
    ]
