# Generated by Django 5.2.3 on 2025-07-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["course", "user"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "подписки",
            },
        ),
    ]
