# Generated by Django 5.2.3 on 2025-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True, default="", upload_to="lesson_videos", verbose_name="Видео"
            ),
        ),
    ]
