# Generated by Django 5.2.3 on 2025-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_lesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, default="", verbose_name="Видео"),
        ),
    ]
