# Generated by Django 5.2.3 on 2025-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="product",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Идентификатор stripe"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Описание урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название урока"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="seq_number",
            field=models.IntegerField(
                default=0, verbose_name="Порядковый номер урока в курсе"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(
                blank=True, default="", verbose_name="Ссылка на видео на youtube.com"
            ),
        ),
    ]
