# Generated by Django 5.2.3 on 2025-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_course_product_alter_lesson_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена курса в рублях"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена урока в рублях"),
        ),
    ]
