# Generated by Django 5.2.3 on 2025-07-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="url_to_buy",
            field=models.URLField(blank=True, verbose_name="Ссылка на покупку курса"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="url_to_buy",
            field=models.URLField(blank=True, verbose_name="Ссылка на покупку урока"),
        ),
    ]
