# Generated by Django 5.2.3 on 2025-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_course_url_to_buy_lesson_url_to_buy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="url_to_buy",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="url_to_buy",
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Идентификатор цены stripe"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_price",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Идентификатор цены stripe"
            ),
        ),
    ]
