# Generated by Django 5.2.3 on 2025-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materials",
            "0013_remove_course_url_to_buy_remove_lesson_url_to_buy_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="product",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Идентификатор stripe"
            ),
        ),
    ]
